- hosts: remote_server
  become: yes
  tasks:
    - name: Load Podman Image from TAR
      command: podman load -i /home/user/myapp.tar

    - name: Stop existing container (if running)
      command: podman stop myapp || true
      ignore_errors: yes

    - name: Remove old container (if exists)
      command: podman rm myapp || true
      ignore_errors: yes

    - name: Run the new container
      command: podman run -d --name myapp -p 8080:8080 myapp:latest
